# These variables are used with the connection: network_cli for Ansible
# Info:   https://docs.ansible.com/ansible/2.9/network/user_guide/platform_nxos.html
#         https://docs.ansible.com/ansible/2.9/plugins/connection/network_cli.html

# ansible_password: C1sco12345
---
ansible_user: developer
ansible_ssh_pass: C1sco12345
